"""Build compact 2-bit antialiased firmware fonts with Pillow 12.3.

Aileron Bold by Sora Sagano is No Rights Reserved:
https://dotcolon.net/fonts/aileron/
Only the generated header is needed to compile the firmware.
"""
from math import ceil
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


FONT_PATH = Path(__file__).resolve().parents[1] / 'assets' / 'fonts' / 'Aileron-Bold.otf'
FONT_SIZES = (10, 11, 13, 16, 18, 22, 32)


def rasterize(size):
    font = ImageFont.truetype(str(FONT_PATH), size)
    top = min(font.getbbox(chr(c))[1] for c in range(32, 127))
    bottom = max(font.getbbox(chr(c))[3] for c in range(32, 127))
    height = bottom - top
    glyphs = []
    for code in range(32, 127):
        char = chr(code)
        left, _, right, _ = font.getbbox(char)
        origin = -min(0, left)
        width = max(1, ceil(font.getlength(char)), right) + origin
        canvas = Image.new('L', (width, height))
        ImageDraw.Draw(canvas).text((origin, -top), char, font=font, fill=255)
        glyphs.append(canvas)
    return height, glyphs


def main():
    output = ['// Generated by tools/build_fonts.py; Aileron Bold by Sora Sagano.',
              '// Source and license: https://dotcolon.net/fonts/aileron/ (No Rights Reserved)',
              '#pragma once', '#include <Arduino.h>', 'namespace Typography {',
              'struct Glyph { uint16_t offset; uint8_t width; };',
              'struct Font { const uint8_t *pixels; const Glyph *glyphs; uint8_t height; };']
    for size in FONT_SIZES:
        height, canvases = rasterize(size)
        pixels, glyphs = [], []
        for canvas in canvases:
            width = canvas.width
            levels = [(value * 3 + 127) // 255 for value in canvas.get_flattened_data()]
            levels += [0] * (-len(levels) % 4)
            glyphs.append((len(pixels), width))
            pixels.extend(sum(levels[i + j] << (6 - j * 2) for j in range(4))
                          for i in range(0, len(levels), 4))
        assert len(pixels) <= 65535, 'Glyph offsets must fit uint16_t'
        assert height <= 255 and all(width <= 255 for _, width in glyphs)
        print(f'Aileron Bold {size}: height {height}, {len(pixels)} bytes')
        output.append(f'static const uint8_t pixels{size}[] PROGMEM = {{')
        output.extend('  ' + ','.join(str(v) for v in pixels[i:i+32]) + ','
                      for i in range(0, len(pixels), 32))
        output.append('};')
        output.append(f'static const Glyph glyphs{size}[] PROGMEM = {{')
        output.extend(f'  {{{offset},{width}}},' for offset, width in glyphs)
        output.extend(['};', f'static const Font font{size} = {{pixels{size}, glyphs{size}, {height}}};'])
    output.append('}  // namespace Typography')
    target = Path(__file__).resolve().parents[1] / 'include' / 'ui_fonts.h'
    target.write_text('\n'.join(output) + '\n', encoding='ascii')
    print(f'Generated {target}')


if __name__ == '__main__':
    main()
